export const STRINGS = {
  ko: {
    title: "민원 찾기",
    step: "진행사항",
    langText: "한/영변환",
    highContrast: "고대비모드",
    largeFont: "큰글씨모드",
    q1: "1.", q1_text: "유형이 어떻게 되시나요?",
    q2: "2.", q2_text: "연령대가 어떻게 되나요?",
    q3: "3.", q3_text: "필요한 서비스는 무엇인가요?",
    q4: "4.", q4_text: "무슨 상황인가요?",
    types: ['외국인', '노인 (65세 이상)', '저소득층', '해당없음'],
    options: {
      age: ['10대', '20대', '30대', '40대', '50대', '60대 이상'],
      service: ['민원', '복지', '주거', '의료', '일자리', '기타/모르겠음'],
    },
    agePlaceholder: "연령을 선택해주세요",
    servicePlaceholder: "서비스를 선택해주세요",
    textareaPlaceholder: "상황을 입력하거나 음성으로 말씀해주세요",
    btnSelect: "입력 선택",
    btnVoice: "음성 인식",
    btnSubmit: "입력 완료",
    cancel: "취소",
    modalAge: "연령 입력",
    modalService: "서비스 입력",
    voiceMain: "말해주세요",
    voiceSubmit: "말하기 완료 (전송)",
  },
  en: {
    title: "Public Service",
    step: "Progress",
    langText: "KO/EN",
    highContrast: "Contrast",
    largeFont: "Big Font",
    q1: "1.", q1_text: "What is your type?",
    q2: "2.", q2_text: "How old are you?",
    q3: "3.", q3_text: "What service do you need?",
    q4: "4.", q4_text: "What is the situation?",
    types: ['Foreigner', 'Senior', 'Low Income', 'N/A'],
    options: {
      age: ['10s', '20s', '30s', '40s', '50s', '60s or older'],
      service: ['Civil Service', 'Welfare', 'Housing', 'Medical', 'Jobs', 'Other/Not sure'],
    },
    agePlaceholder: "Select Age",
    servicePlaceholder: "Select Service",
    textareaPlaceholder: "Enter situation or speak",
    btnSelect: "Select",
    btnVoice: "Voice",
    btnSubmit: "Complete",
    cancel: "Cancel",
    modalAge: "Age Input",
    modalService: "Service Input",
    voiceMain: "Please speak",
    voiceSubmit: "Finish (Send)",
  },
} as const;

export type QaStrings = typeof STRINGS.ko;
